language: php

dist: trusty

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  global:
    - APP_ENV=test
    - APP_DEBUG=1
    - APP_SECRET=secret
    - CI_BUILD_NUMBER="$TRAVIS_BUILD_NUMBER"

php:
  - '7.1'

before_script:
  - travis_retry composer install ${COMPOSER_FLAGS} --no-interaction

script:
  - vendor/bin/simple-phpunit

after_success:
  - vendor/bin/coveralls
