# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    console.application:
        class: AppBundle\Console\Application
        arguments:
            - 'nab3a'
            - "@=parameter('kernel.environment') ~ (parameter('kernel.debug') ? '/debug' : '')"

        calls:
            - [ setDispatcher, [ '@event_dispatcher' ] ]

    console.input:
        class: Symfony\Component\Console\Input\ArgvInput

    console.output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    console.command:
        abstract: true
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setLogger, [ '@?logger' ] ]
        tags:
            - { name: monolog.logger }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
