# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Component\Console\Input\ArgvInput: ~
    Symfony\Component\Console\Output\ConsoleOutput: ~
    Symfony\Component\Console\Output\OutputInterface: '@Symfony\Component\Console\Output\ConsoleOutput'
    Symfony\Component\Console\Input\InputInterface: '@Symfony\Component\Console\Input\ArgvInput'
    Clue\JsonStream\StreamingJsonParser:
        shared: false

    App\Command\:
        resource: '../src/Command/{PipeCommand.php,ReadStreamCommand.php}'
        calls:
            - [ setContainer, ['@service_container'] ]
            - [ setLogger, [ '@?logger' ] ]
        tags: ['nab3a.console.command','monolog.logger']

    App\Console\Application:
        arguments:
            - 'nab3a'
            - "@=parameter('kernel.environment') ~ (parameter('kernel.debug') ? '/debug' : '')"

        calls:
            - [ setDispatcher, [ '@event_dispatcher' ] ]

    nab3a.twitter.guzzle.client:
        class: GuzzleHttp\Client
        arguments:
            -
                base_uri: https://stream.twitter.com/1.1/
                auth: oauth
                decode_content: 'deflate, gzip'
                stream: true
                on_stats: [ '@App\Guzzle\Emitter', 'onStats' ]
                on_headers: [ '@App\Guzzle\Emitter', 'onHeaders' ]

    GuzzleHttp\Subscriber\Oauth\Oauth1:
        class: GuzzleHttp\Subscriber\Oauth\Oauth1
        arguments:
            -
                consumer_key:    '%env(TWITTER_CONSUMER_KEY)%'
                consumer_secret: '%env(TWITTER_CONSUMER_SECRET)%'
                token:           '%env(TWITTER_ACCESS_TOKEN)%'
                token_secret:    '%env(TWITTER_ACCESS_TOKEN_SECRET)%'
        tags:
            - { name: guzzle.middleware, client: nab3a.twitter.guzzle.client, middleware_name: oauth }

    App\Guzzle\Emitter:
        calls:
            - [ setLogger, [ '@?logger']]
        tags:
            - { name: monolog.logger, channel: guzzle }
        public: false

    React\EventLoop\LoopInterface:
        factory: ['React\EventLoop\Factory','create']

    MKraemer\ReactPCNTL\PCNTL: ~

    App\Process\ChildProcess: ~

    App\Twitter\MessageEmitter: ~

    App\Console\LoggerHelper:
        arguments: ['@=service(''Symfony\\Component\\Console\\Output\\ConsoleOutput'').getErrorOutput()']
        calls:
            - [ setContainer, ['@service_container'] ]

    guzzle_handler:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        calls:
            - [ 'remove', ['http_errors']]
            - [ 'remove', ['allow_redirects']]
            - [ 'remove', ['cookies']]
#            - [ 'remove', ['prepare_body']]

    nab3a.guzzle.client:
        class: GuzzleHttp\Client
        public: false
        arguments:
            -
                on_stats: [ '@App\Guzzle\Emitter', 'onStats' ]
                on_headers: [ '@App\Guzzle\Emitter', 'onHeaders' ]

    nab3a.guzzle.handler_stack:
        class: GuzzleHttp\HandlerStack
        public: false
        shared: false

    nab3a.guzzle.client.handler:
        class: GuzzleHttp\HandlerStack
        factory: ['@nab3a.guzzle.client', 'getConfig']
        arguments: ['handler']

    nab3a.guzzle.middleware.log:
        class: Closure
        factory: [ GuzzleHttp\Middleware, log ]
        arguments: [ '@?logger', '@GuzzleHttp\MessageFormatter' ]
        tags:
            - { name: monolog.logger, channel: guzzle }
            - { name: guzzle.middleware, client: nab3a.guzzle.client, middleware_name: log, after: retry }
            - { name: guzzle.middleware, client: nab3a.twitter.guzzle.client, middleware_name: log, after: retry }
        public: false
        shared: false

    GuzzleHttp\MessageFormatter:
        arguments: [ '@=constant(''GuzzleHttp\\MessageFormatter::CLF'')' ]
        public: false

    nab3a.guzzle.middleware.retry:
        class: Closure
        public: false
        shared: false
        factory: [ App\Guzzle\RetryMiddleware, retry ]

    nab3a.twitter.guzzle.middleware.retry:
        class: Closure
        public: false
        shared: false
        factory: [ App\Guzzle\RetryMiddleware, retry ]
        tags:
            - { name: guzzle.middleware, client: nab3a.twitter.guzzle.client, middleware_name: retry }

    Symfony\Bridge\Monolog\Handler\ConsoleHandler:
        calls:
            - [ setFormatter, [ '@=service(''Symfony\\Component\\Console\\Input\\ArgvInput'').hasParameterOption(''--child'') ? service(''Monolog\\Formatter\\LogglyFormatter'') : service(''Symfony\\Bridge\\Monolog\\Formatter\\ConsoleFormatter'')'] ]
        tags:
            - { name: kernel.event_subscriber }

    Symfony\Bridge\Monolog\Formatter\ConsoleFormatter: ~

    Monolog\Formatter\LogglyFormatter:
        arguments: ['@=constant(''Monolog\\Formatter\\JsonFormatter::BATCH_MODE_NEWLINES'')', true]
        public: true

    App\RabbitMq\EnqueueTweetPlugin:
        class: App\RabbitMq\EnqueueTweetPlugin
        arguments:
            - '@old_sound_rabbit_mq.twitter_producer'
            - ''
            - { content_type: 'application/json' }
        public: false
        tags:
            - { name: evenement.plugin, id: App\Twitter\MessageEmitter }

    App\Logger\LogMessagePlugin:
        arguments:
            -
                delete:           ~
                tweet:            ~
        calls:
            - [ setLogger, [ '@?logger' ] ]
        tags:
            - { name: monolog.logger, channel: twitter }
            - { name: evenement.plugin, id: App\Twitter\MessageEmitter }
        public: false

    App\Stream\Eep:
        arguments:
            - !service
                  class: React\EEP\Window\Periodic
                  factory: ['@App\Stream\PeriodicFactory', makeStatusCounter ]
            - !service
                  class: React\EEP\Window\Periodic
                  factory: ['@App\Stream\PeriodicFactory', makeStatusAverager ]
            - !service
                  class: React\EEP\Window\Periodic
                  factory: ['@App\Stream\PeriodicFactory', makeIdleTimeTracker ]
        tags:
            - { name: evenement.plugin, id: App\Twitter\MessageEmitter }
            - { name: event_loop.plugin }

    App\Stream\PeriodicFactory:
        calls:
            - [ setLogger, ['@logger']]

    Monolog\Processor\MemoryUsageProcessor:
        arguments: [ true, false ]
        tags:
            - { name: monolog.processor }

#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
